title: vic485's Blog
email:
description: >- # this means to ignore newlines until "baseurl:"
  A software developer's blog about photography, cars, computers, and other interests.
twitter_username: thevic485
github_username: vic485
minimal_mistakes_skin: neon
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Victor Fugazzotto"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Software developer and car enthusiast with a new interest in photography."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://vic485.xyz"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/thevic485"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vic485"
    - label: "Main Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/vic485"
    - label: "Photography Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/taron_iii_photo"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/thevic485"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vic485"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/vic485"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
